// Generated by CoffeeScript 1.6.3
(function() {
  var app, main, _controllerContent, _di, _dispatcher;

  response.addContent("Content-type: text/html\r\n\r\n");

  _di = require('./lib/di.coffee');

  _dispatcher = require('./lib/dispatcher.coffee');

  _controllerContent = require('./controller/content.coffee');

  main = (function() {
    function main() {}

    main.prototype.di = null;

    main.prototype.getContainer = function() {
      if (this.di) {
        return this.di;
      }
      this.di = new _di;
      this.di.configure({
        factories: {
          dispatcher: function(di) {
            return new _dispatcher(di);
          },
          controllerContent: function(di) {
            return new _controllerContent;
          }
        }
      });
      return this.di;
    };

    main.prototype.handle = function(request) {
      return this.getContainer().get('dispatcher')().dispatchRoute(request);
    };

    return main;

  })();

  app = new main;

  app.handle({
    controller: 'Content'
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
