// Generated by CoffeeScript 1.6.3
(function() {
  var dispatcher;

  dispatcher = (function() {
    function dispatcher(di) {
      this.di = di;
    }

    dispatcher.prototype.dispatch = function(controller, action) {
      return this.dispatchRoute({
        action: action,
        controller: controller
      });
    };

    dispatcher.prototype.dispatchRoute = function(route) {
      var e;
      try {
        return this.di.get('controller' + route.controller)().dispatch(route);
      } catch (_error) {
        e = _error;
        if (e.msg) {
          console.log(e.msg);
        }
        if (e.message) {
          console.log(e.message);
        }
        console.log(e);
        throw "Controller " + route.controller + " doesnt exists?";
      }
    };

    return dispatcher;

  })();

  if (typeof module !== "undefined") {
    module.exports = dispatcher;
  }

}).call(this);

/*
//@ sourceMappingURL=dispatcher.map
*/
