// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = (function() {
    function _Class() {}

    _Class.prototype.greet = function(name) {
      return 'hello!! ' + name;
    };

    return _Class;

  })();

}).call(this);

/*
//@ sourceMappingURL=greeter.map
*/
