// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = (function() {
    function _Class(di) {
      this.di = di;
    }

    _Class.prototype.dispatch = function(controller, action) {
      return this.dispatchRoute({
        action: action,
        controller: controller
      });
    };

    _Class.prototype.dispatchRoute = function(route) {
      var e;
      try {
        return this.di.get('controller' + route.controller)().dispatch(route);
      } catch (_error) {
        e = _error;
        if (e.msg) {
          console.log(e.msg);
        }
        if (e.message) {
          console.log(e.message);
        }
        console.log(e);
        throw "Controller " + route.controller + " doesnt exists?";
      }
    };

    return _Class;

  })();

}).call(this);

/*
//@ sourceMappingURL=dispatcher.map
*/
