// Generated by CoffeeScript 1.6.3
(function() {
  var app, main, _controllerContent, _controllerFooter, _controllerLeft, _di, _dispatcher, _serviceGreeter;

  _di = require('./lib/di.coffee');

  _dispatcher = require('./lib/dispatcher.coffee');

  _controllerLeft = require('./controller/left.coffee');

  _controllerContent = require('./controller/content.coffee');

  _controllerFooter = require('./controller/footer.coffee');

  _serviceGreeter = require('./service/greeter.coffee');

  main = (function() {
    function main() {}

    main.prototype.di = null;

    main.prototype.getContainer = function() {
      if (this.di) {
        return this.di;
      }
      this.di = new _di;
      this.di.configure({
        factories: {
          dispatcher: function(di) {
            return new _dispatcher(di);
          },
          controllerLeft: function(di) {
            return new _controllerLeft(di.get('serviceGreeter'));
          },
          controllerContent: function(di) {
            return new _controllerContent;
          },
          controllerFooter: function(di) {
            return new _controllerFooter;
          },
          serviceGreeter: function() {
            return new _serviceGreeter;
          }
        }
      });
      return this.di;
    };

    main.prototype.handle = function(request) {
      return this.getContainer().get('dispatcher')().dispatchRoute(request);
    };

    return main;

  })();

  app = new main;

  $('document').ready(function() {
    return $('.app_controller').each(function(i, el) {
      return app.handle({
        controller: $(el).data('controller'),
        dom: $(el)
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
