// Generated by CoffeeScript 1.6.3
(function() {
  var abstractController;

  abstractController = (function() {
    function abstractController() {}

    abstractController.prototype.getDom = function() {
      return this.dom;
    };

    abstractController.prototype.dispatch = function(req) {
      if (req.action == null) {
        req.action = 'index';
      }
      if (typeof req.controller === "undefined") {
        throw {
          msg: 'request needs a controller',
          request: req
        };
      }
      if (!this[req.action + 'Action']) {
        throw {
          msg: 'action ' + req.action + 'Action' + ' for controller ' + req.controller + ' doesn\'t exists',
          request: req
        };
      }
      this.dom = req.dom || {};
      return this[req.action + 'Action'](req);
    };

    return abstractController;

  })();

  module.exports = abstractController;

}).call(this);

/*
//@ sourceMappingURL=abstract.map
*/
