// Generated by CoffeeScript 1.6.3
(function() {
  var controllerHello,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  controllerHello = (function(_super) {
    __extends(controllerHello, _super);

    function controllerHello(serviceGreeter) {
      this.serviceGreeter = serviceGreeter;
    }

    controllerHello.prototype.indexAction = function(req) {
      console.log('YAAYYYY!!');
      return console.log(this.serviceGreeter().greet('folks'));
    };

    return controllerHello;

  })(controllerAbstract);

}).call(this);

/*
//@ sourceMappingURL=hello.map
*/
