// Generated by CoffeeScript 1.6.3
(function() {
  var helloController;

  helloController = (function() {
    function helloController() {}

    helloController.prototype.indexAction = function(req) {
      return console.log('YAAYYYY!!');
    };

    return helloController;

  })();

}).call(this);

/*
//@ sourceMappingURL=hello.map
*/
