// Generated by CoffeeScript 1.6.3
(function() {
  var main;

  main = (function() {
    function main() {}

    main.prototype.di = null;

    main.prototype.getContainer = function() {
      if (this.di == null) {
        return this.di;
      }
      this.di = new diContainer;
      this.di.configure({
        factories: {
          dispatcher: function(di) {
            return new dispatcher(di);
          },
          helloController: function() {
            return new helloController;
          }
        }
      });
      return this.di;
    };

    main.prototype.handle = function(request) {
      return this.getContainer().get('dispatcher')().dispatch(request.controller);
    };

    return main;

  })();

  (new main).handle({
    controller: 'hello'
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
