// Generated by CoffeeScript 1.6.3
(function() {
  var abstractController,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  abstractController = require('./abstract.coffee');

  module.exports = (function(_super) {
    __extends(_Class, _super);

    function _Class(serviceGreeter) {
      this.serviceGreeter = serviceGreeter;
    }

    _Class.prototype.indexAction = function(req) {
      return this.dom.html('Controller Content ...');
    };

    return _Class;

  })(abstractController);

}).call(this);

/*
//@ sourceMappingURL=content.map
*/
