// Generated by CoffeeScript 1.6.3
(function() {
  var abstractController, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  abstractController = require('./abstract.coffee');

  module.exports = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      _ref = _Class.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    _Class.prototype.indexAction = function(req) {
      return this.dom.html('Controller Left ...');
    };

    return _Class;

  })(abstractController);

}).call(this);

/*
//@ sourceMappingURL=left.map
*/
